const CONSTANTS = {
  THEME: {
    LIGHT: 'LIGHT',
    DARK: 'DARK',
  },
  LANGUAGE: {
    EN: 'EN',
    PT: 'PT',
    UA: 'UA',
  },
  TRANSLATIONS: {
    EN: {
      name: 'ENGLISH',
      home: 'Home',
      users: 'Users',
      counter: 'Counter',
      load: 'Load',
      form: 'Form',
      AutoClick: 'AutoClick',
      Time: 'Time',
      Left: 'Left',
      add: 'add',
      Change: 'Change',
      Mode: 'Mode',
      Current: 'Current',
      step: 'step',
      events: 'events',
      phones: 'phones',
      date: 'date',
      happy: 'happy',
      birthday: 'birthday',
      new: 'new',
      year: 'year',
    },
    PT: {
      name: 'PORTUGUES',
      home: 'Página Inicial',
      users: 'Usuários',
      counter: 'Contador',
      load: 'Carregar',
      form: 'Formulário',
      AutoClick: 'Tempo Restante',
      Time: 'Tempo',
      Left: 'Restante',
      add: 'adicionar',
      Change: 'Mudar',
      Mode: 'Modo',
      Current: 'Atual',
      step: 'passo',
      events: 'eventos',
      phones: 'telefones',
      date: 'data',
      happy: 'feliz',
      birthday: 'Aniversário',
      new: 'nowo',
      year:'ano',
    },
    UA: {
      name: 'УКРАЇНСЬКА',
      home: 'Головна',
      users: 'Користувачі',
      counter: 'Лічильник',
      load: 'Завантажити',
      form: 'Форма',
      AutoClick: 'АвтоКлік',
      Time: ' Часу',
      Left: 'Залишилось',
      add: 'додати',
      Change: 'Змінити ', 
      Mode: 'Режим',
      Current: 'Поточний ',
      step: 'крок',
      events: 'Події',
      phones: 'Телефони',
      date: 'Дата',
      happy: 'щасливого',
      birthday: ' Народження',
      new: 'Новий',
      year:'Рік',
    },
  },
};

export default CONSTANTS;
